language: python

python:
    - "3.6"
cache:
    pip

install:
    - pip install -r requirements.txt
    - pip install coverage
    - pip install coveralls
    - pip install pytest-cov
    
script:
    py.test --cov-report= --cov=v1 tests/

after_success:
- coveralls